name: Pre-commit Checks

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install ".[dev]"
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.1
